### ISSUE TITLE
Being able to loop the discs

### ISSUE THREAD

**Issue by GNamimates** [henkelmax/audio-player#24]
**Is your feature request related to a problem? Please describe.**
me and my friends have been wanting to add background music depending on where we are around our server, at first we used redstone, but it keeps dis-aligning, causing it to sometimes stop too early or restart too late

**Describe the solution you'd like**
4th argument for loop as a boolean when applying the music to the disc
`/audioplayer musicdisc UUID <name> <loop | boolean>`

**Describe alternatives you've considered**
or comparitors stop outputting signal when the discs finishes

**Additional context**
even if you dont add this, still thank you for making the mod!, it enhanced me and my friend's experience ❤️

**Comment by henkelmax** [comment]
Not sure how to handle world reloads/chunk unloading with looping sounds...

**Comment by GNamimates** [comment]
oh, maybe comparitor outputs stop when its done playing?

**Comment by henkelmax** [comment]
What do you mean?

**Comment by henkelmax** [comment]
Not sure if that will break a lot of existing redstone contraptions...

**Comment by GNamimates** [comment]
jukeboxes are never used on redstone contraptions, from what I see on redstone communities, since there are alot more better alternatives like cauldron and the composter, which can be moved by pistons and are cheaper.

I am sure nobody would use jukeboxes on redstone,
but if someone did and are using your mod as well, it will mostly work the same way, and will most likely notice the redstone output stops once they hear the music stop

**Comment by GNamimates** [comment]
just my idea, if you dont wanna add this im alright 😁

**Comment by henkelmax** [comment]
I thought a bit what downsides there are if discs would infinitely loop...

1. A lot of jukeboxes infinitely looping would mean there is a separate thread for all of them and the server needs to handle all these constantly.
2. It would also cause a lot of issues with unloading chunks and reloading the world.
3. A comparator signal when finished playing might be hard to implement, since the game itself is not aware of the playing audio and you would need to have a callback outside of the main game thread.

For now I won't add this feature, but I will keep it in mind and will try to add it once I have a solution for the issues.
