### ISSUE TITLE
[Enchancement] There is no command to get the existing sounds ?

### ISSUE THREAD

**Issue by Wolphwood** [henkelmax/audio-player#61]
It would be useful to have a command that lists the sounds available.

A file could be present to list the sounds?
```
[
  { filename: "original_name.mp3", id: "the uuid", duration: "sound duration in ms", uploader: "data containing who upload this ?" },
  { filename: "original_name.wav", id: "the uuid", duration: "2700", uploader: "data containing who upload this ?" },
  
]
```

The command :
`/audioplayer list`

The ouput :
```
Sound list :
 - The sound name (17.5s) // => Display Id and owner on hover, copy id into clipboard on click.
```
or maybe like that ?
```
Sound list :
 [id] [disc] [horn] The sound name (17.5s)
```
with "id", "disc" and "horn" translated separately than the main message
main message => `[%s] [%s] [%s] %s (%s)`
so people (like me) can replace text 'disc' or 'horn' with custom emojis (with ressource pack)

**Comment by henkelmax** [comment]
You can get the id of an item by using the "/audioplayer id" command

**Comment by yuli6669** [comment]
Getting all already downloaded songs would be useful tho. And using file names instead of IDs. This would make it more user-friendly

**Comment by henkelmax** [comment]
> Getting all already downloaded songs would be useful tho. And using file names instead of IDs. This would make it more user-friendly

This is already implemented.

**Comment by yuli6669** [comment]
oh, yes, sorry, didn't read repo thoroughly

**Comment by breadbyte** [comment]
> This is already implemented.

The feature being requested does not seem to be implemented. It is not documented anywhere how to get the list of _all_ existing sounds _without_ their corresponding disc (`/audioplayer id` requires that you have a disc with an existing sound in the world), and I could not find where the requested feature is implemented.

As a server administrator, I would like to get all of the currently existing sounds and their corresponding IDs in the server for both content moderation and technical purposes.

I've since figured out that this information is accessible in `\world\audio_player_data` (undocumented), but it would still be nice to have this feature be accessible in game.
