### ISSUE TITLE
Volume and playing issue

### ISSUE THREAD

**Issue by schwifty762** [henkelmax/audio-player#86]
### Bug description

I know this is still in alpha but whenever you play a custom disc the volume settings don't work for the custom disk at all. You could lower the volume of jukeboxes all the way down and it'll still be very loud. Another issue that I've seen is that when ever you pause the game the music will still keep going, and I'm playing in a single player server, so when I do pause everything else does except the music. I don't really know if this is intentional or there's no other way around these issues but I guess I'm just letting you know incase it isn't intentional.

### Minecraft version

1.21

### Simple Voice Chat version

1.21-2.5.19

### Mod version

1.21-1.10.2

### Mod loader and version

Fabric Loader 0.100.6 1.21

### Steps to reproduce

1. Click "escape"
3. Click on "Options"
4. Click on "Music and Sounds"
5. Click on the slider for either the "Jukebox" or the "Master Volume" and drag left to lower the volume

### Expected behavior

For the volume issue i expected it to lower the volume its at, cause it is pretty loud, and then for the playing and pausing issue, whenever the game paused I expected it to pause the music and then resume once I unpaused the game.

### Log files

<script src="https://gist.github.com/schwifty762/a13ed8733904c099cdb68cb2ec936a57.js"></script>

**Comment by henkelmax** [comment]
1. This is a server side mod. This isn't meant to be used in single player
2. Due to the reason its using voice chat it will continue playing in realtime, since it is meant to run on a server not in singleplayer
3. This doesn't use the jukebox volume slider, since the mod uses voice chat to play. You need to adjust the custom disc volume in the voice chat volume settings.
